version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repusense-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - repusense-network

networks:
  repusense-network:
    driver: bridge 